#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
#  arfedora-gtmacos
#  
#  Copyright 2017 youcefsourani <youssef.m.sourani@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
from subprocess import check_output
import sys
from pwd import getpwuid
import os
import gi
from gi.repository import Gio,GLib
import dbus
from time import sleep



default_terminal_profile=eval(check_output("gsettings get org.gnome.Terminal.ProfilesList list",shell=True).decode("utf-8").strip())[0]



extensions_to_enable = ["user-theme@gnome-shell-extensions.gcampax.github.com",
                        "clipboard-indicator@tudmotu.com",
                        "CoverflowAltTab@palatis.blogspot.com",
                        "dash-to-dock@micxgx.gmail.com",
                        "drive-menu@gnome-shell-extensions.gcampax.github.com",
                        "EasyScreenCast@iacopodeenosee.gmail.com",
                        "gTile@vibou",
                        "simplenetspeed@biji.extension"]

             
       

gsettings = [ ["org.gnome.desktop.background"          , "show-desktop-icons",GLib.Variant('b',False)] ,
			  ["org.gnome.desktop.background"           , "picture-uri",GLib.Variant('s',"file:///usr/share/OSX-Arc-White/extra/mountains.png")] ,
			  ["org.gnome.desktop.screensaver"          , "picture-uri",GLib.Variant('s',"file:///usr/share/OSX-Arc-White/extra/xmountain.jpg")] ,
			  ["org.gnome.desktop.interface"            , "icon-theme",GLib.Variant('s',"macOS")] ,
			  ["org.gnome.shell.extensions.user-theme"  , "name",GLib.Variant('s',"OSX-Arc-White")] ,
			  ["org.gnome.desktop.interface"            , "gtk-theme",GLib.Variant('s',"OSX-Arc-White")] ,
			  ["org.gnome.desktop.interface"            , "enable-animations",GLib.Variant('b',True)] ,
			  ["org.gnome.desktop.wm.preferences"       , "button-layout",GLib.Variant('s',":minimize,close")] ,
			  ["org.gnome.desktop.interface"            , "cursor-theme",GLib.Variant('s',"Breeze_Snow")] ,
			  ["org.gnome.Terminal.Legacy.Settings"     , "theme-variant",GLib.Variant('s',"light")] ,
			  ["org.gnome.Terminal.Legacy.Settings"     , "default-show-menubar",GLib.Variant('b',False)] ,
			  ["org.gnome.shell.extensions.dash-to-dock", "dock-position",GLib.Variant('s',"BOTTOM")]]

			
gnome_terminal = [["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "use-theme-colors" , GLib.Variant('b',False)] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "use-system-font" , GLib.Variant('b',False)] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "background-color" , GLib.Variant('s',"#FFFFFF")] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "font" , GLib.Variant('s',"Monospace 15")] ,\
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "foreground-color" , GLib.Variant('s',"#5940BF")] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "cursor-background-color" , GLib.Variant('s',"#EF2929")] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "cursor-colors-set" ,GLib.Variant('b',True)] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "background-transparency-percent" , GLib.Variant('i',20)] ,
                  ["/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile) , "use-transparent-background" , GLib.Variant('b',True)]
                  ]
			
class GnomeShell(object):
	def __init__(self,list_setting):
		self.__list_setting           = list_setting
		self.__bus                    = dbus.SessionBus()
		self.__id                     = "org.gnome.Shell"
		self.__object                 = "/org/gnome/Shell"
		self.__interface_properties   = "org.freedesktop.DBus.Properties"
		self.__interface_extensions   = "org.gnome.Shell.Extensions"
		self.__proxy                  = self.__bus.get_object(self.__id,self.__object)
		self.__interface_p            = dbus.Interface(self.__proxy,self.__interface_properties)
		self.__interface_e            = dbus.Interface(self.__proxy,self.__interface_extensions)
		self.__settings = Gio.Settings(schema='org.gnome.shell')
		self.__settings.delay()
		self.__settings.sync()
		self.__list_setting.append(self.__settings)
		
	def version(self):
		return self.__interface_p.Get(self.__interface_extensions,"ShellVersion")
	
	def list_extensions(self):
		result = {}
		for k,v in self.__interface_e.ListExtensions().items():
			result.setdefault(k,True if v["state"]==1.0 else False)
		return result
		
	def list_enabled_extensions(self):
		result = []
		for k,v in self.__interface_e.ListExtensions().items():
			if v["state"]==1.0:
				result.append(k)
		return result

	def list_disabled_extensions(self):
		result = []
		for k,v in self.__interface_e.ListExtensions().items():
			if v["state"]!=1.0:
				result.append(k)
		return result
		
	def enable_extensions(self,extensions):
		ex = self.__settings.get_strv("enabled-extensions")
		for extension in extensions:
			if extension not in ex:
				ex.append(extension)

		self.__settings.set_strv("enabled-extensions", ex)

		
	def disable_extensions(self,extensions):
		ex = self.__settings.get_strv("enabled-extensions")
		for extension in extensions:
			while extension  in ex:
				ex.remove(extension)
		self.__settings.set_strv("enabled-extensions", ex)
		

def init_check():
	if os.getuid()==0:
		sys.exit("Run Script Without Root Permissions.")

if __name__ == "__main__":
	init_check()
	list_setting = []
	if "--time-out" in sys.argv:
		try:
			speed = float(sys.argv[sys.argv.index("--time-out")+1])
			if speed <= 0:
				speed = 0.3
			elif speed > 5:
				speed = 0.3
		except:
			speed = 0.3
	else:
		speed = 0.3
	
	
	try:
		gnome = GnomeShell(list_setting)
	except:
		sys.exit("Gnome Shell Not Found.")
	
	gnome.disable_extensions(gnome.list_extensions().keys())
	gnome.enable_extensions(extensions_to_enable)


	for i in gsettings:
		setting = Gio.Settings(i[0])
		setting.delay()
		setting.sync()
		list_setting.append(setting)
		setting.set_value(i[1],i[2])
		
		
	setting = Gio.Settings.new_with_path("org.gnome.Terminal.Legacy.Profile","/org/gnome/terminal/legacy/profiles:/:{}/".format(default_terminal_profile))
	setting.delay()
	setting.sync()
	list_setting.append(setting)
	for m in gnome_terminal:
		setting.set_value(m[1],m[2])
		
		
	for s in list_setting:
		sleep(speed)
		s.apply()

print("\nDone.")
